logging.level.root=info
## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring.jpa.database=POSTGRESQL
spring.datasource.url=jdbc:postgresql://localhost:5432/inventory
spring.datasource.username=postgres
spring.datasource.password=112711

# The SQL dialect makes Hibernate generate better SQL for the chosen database
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect

spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false

# Enable SSL
server.ssl.enabled=true

# Path to your keystore (ensure it's in your classpath or provide an absolute path)
server.ssl.key-store=classpath:keystore.p12

# Keystore password (the one you set during the keystore generation)
server.ssl.key-store-password=112711

# Keystore type (PKCS12 is a common choice)
server.ssl.key-store-type=PKCS12

# Key alias (same as the one you used during keystore creation)
server.ssl.key-alias=inventory
# Set the server port to 443 (default HTTPS port) or any other port you prefer
server.port=8443